### ISSUE TITLE
Japanese symbols show as '?'

### ISSUE THREAD

**Issue by hdpe1399** [Willy-Kimura/SharpClipboard#1]
does this plugin work with unicode characters?

**Comment by hdpe1399** [comment]
for example, this symbol "覚"
i can copy well to the notepad 

but when i use `MessageBox.Show(clipboard.ClipboardText);`

it just shows a question mark

**Comment by Willy-Kimura** [comment]
Hi @hdpe1399 

I've just updated the component with support for **Unicode** symbols and characters.
It's now working.
