### ISSUE TITLE
Unable to set window title

### ISSUE THREAD

**Issue by CaledoniaProject** [Willy-Kimura/SharpClipboard#12]
SharpClipboard library will create a hidden window with title `{SharpClipboard}`, can you expose a method to change the title?

**Comment by Willy-Kimura** [comment]
The said window is by default hidden from the end-user.
Is it in any way visible whenever you start your application?

`Edit`
In the next release, I'll be removing the window title.

**Comment by CaledoniaProject** [comment]
No, it's not visible, it's just a computer forensics issue.
It's best to be configurable than an empty string ..

**Comment by Willy-Kimura** [comment]
As from version `3.5.1`, I'll be providing a static property `HandleCaption`, that allows you to change the invisible window's caption globally.
