### ISSUE TITLE
ClipboardFiles not being cleared properly.

### ISSUE THREAD

**Issue by MuMugs** [Willy-Kimura/SharpClipboard#14]
ClipboardHandle.cs is not clearing SharpClipboardInstance.ClipboardFiles before adding files, so all the time you copy files to the clipboard its just gets bigger and bigger.

Simple .Clear() on line 198 will fix this problem.

Regards

**Comment by Willy-Kimura** [comment]
And just to think I had included that...
Expect this in the next release.

Many thanks.

Best Regards, WK.

**Comment by Willy-Kimura** [comment]
Update to `v3.5.2` now available.
