### ISSUE TITLE
It always issues ClipboardChanged event when my application start.

### ISSUE THREAD

**Issue by GF-Huang** [Willy-Kimura/SharpClipboard#15]
How to make it only issues `ClipboardChanged` event when first time copy rather then my application start.

**Comment by Willy-Kimura** [comment]
Simply set the property `ObserveLastEntry` to false.

**Comment by GF-Huang** [comment]
So does the comment reversed?

![image](https://user-images.githubusercontent.com/4510984/88562891-da3d1f80-d063-11ea-908b-dfe58f7ba6ba.png)

**Comment by Willy-Kimura** [comment]
Yes I noticed that too.
Will sort that out in the next release.

**Comment by GF-Huang** [comment]
OK, it works correct after I set it to `false`, thank you.
