### ISSUE TITLE
ClipboardText property is not cleaned when the Clipboard is cleared. 

### ISSUE THREAD

**Issue by C1rdec** [Willy-Kimura/SharpClipboard#19]
I found that the `ClipboardText` property is not cleaned after a `System.Window.Clipboard.Clear()`.

**Comment by Willy-Kimura** [comment]
By default, the `ClipboardText` property acts like a cache for storing the last copied clipboard text, meaning that it does not directly reference the clipboard's contents.

I'll see what I can do in the next release.
For now, try using the `Clipboard.ContainsText()` method before using the `ClipboardText` property.

Ideas:
- Let each clipboard object have its last clipboard variant property, e.g. `LastClipboardText`.
- Automatically update each clipboard object based on the current clipboard's contents.

**Comment by C1rdec** [comment]
As of 3.5.2 `Clipboard.ContainsText()` does not exist.

**Comment by Willy-Kimura** [comment]
No, I meant using `System.Windows.Forms.Clipboard`. The class mentioned contains the method `ContainsText()`, e.g. `System Windows.Forms.ContainsText()`.

**Comment by C1rdec** [comment]
I end up keeping the last value of the clipboard on my side. You could add the last value property that you were talking.
But I think it would make sense that you keep a way to have those values up to date on your side. ❤️

**Comment by C1rdec** [comment]
Btw is there a way I can try this before buying?
https://gumroad.com/l/qmWSh

**Comment by Willy-Kimura** [comment]
Thanks for the input. Will try that out.

As for TrialMaker, yes you can definitely reach out for a trial preview of the library. I'll also provide complete documentation and a sample demo just to give you a preview of what it looks like and how it works.
