### ISSUE TITLE
Folder is recognize as a file, so I wonder what is ContentType.Other actually mean in this case. I've thought that folder is detected as ContentType.Other

### ISSUE THREAD

**Issue by tranhuudang** [Willy-Kimura/SharpClipboard#27]
![image](https://user-images.githubusercontent.com/96557038/169940130-5a340361-09ef-43b9-ab17-d73ae657797d.png)

**Comment by Willy-Kimura** [comment]
Both files and folders fall collectively under **file systems**, in this case the **Windows File System** (WFS), and logically therefore fall under the same enumeration as `ContentTypes.Files`. Folders are simply put a collection or grouping of separate files in a system. `ContentTypes.Other` targets data types that are complex in nature or contain special formatting information (e.g. email attachments) which would ideally not be recognized by most applications.

Hope this helps.
