### ISSUE TITLE
Throws ExternalException when closing outlook with large image in clipboard.

### ISSUE THREAD

**Issue by bobend** [Willy-Kimura/SharpClipboard#3]
### Steps to reproduce:
1. Run SharpClipboardPreview.Tests
2. Open Outlook
3. Copy a large image from inside a message body.
4. Close Outlook
5. ClipboardHandle throws in `protected override void WndProc(ref Message m)` when trying to call `Clipboard.GetDataObject();` 

### Exception:
`System.Runtime.InteropServices.ExternalException: 'Requested Clipboard operation did not succeed.'`

**Comment by Willy-Kimura** [comment]
Great. I've not managed to reproduce the issue but have seen the likely possible outcomes.
I've tested the code though with all other supported formats; works fine.

Merging changes...
