### ISSUE TITLE
ClipboardChanged fires for all Types

### ISSUE THREAD

**Issue by satyris** [Willy-Kimura/SharpClipboard#5]
Although SharpClipboard is set to only observe Texts, the event fires if Images/Other file types are copied using latest Version 3.1.0:

_clipboard.ObservableFormats.Texts = true;
_clipboard.ObservableFormats.Files = false;
_clipboard.ObservableFormats.Images = false;
_clipboard.ObservableFormats.Others = false;

**Comment by Willy-Kimura** [comment]
Seems there might be a recursion issue (with the _fail-retry_ task) in the latest update when an exception occurs causing all the events to be invoked. 

Have you tried enabling then disabling monitoring after setting the `ObservableFormats` using the `MonitorClipboard` property?

**Comment by satyris** [comment]
I'm currently using something like this:
`public partial class MainWindow 
{
    private SharpClipboard _clipboard = new SharpClipboard();

    public MainWindow()
    {
        _clipboard.InitializeLifetimeService();//Added for testing; didn't change the behavior
        _clipboard.ObservableFormats.Texts = true;
        _clipboard.ObservableFormats.Files = false;
        _clipboard.ObservableFormats.Images = false;
        _clipboard.ObservableFormats.Others = false;
        _clipboard.ClipboardChanged += _clipboard_ClipboardChanged;
        _clipboard.StartMonitoring();
    }

    private void Options_MonitorClipboardChanged(object sender, EventArgs e)
    {
        _clipboard.MonitorClipboard = Options.MonitorClipboard;
    }
}`

**Comment by Willy-Kimura** [comment]
Seems it works fine on my end.

Try comparing yours with the Tests project and see the minor changes you can make. Also, you don't need to use the inherited property `InitializeLifetimeService`.

**Comment by Willy-Kimura** [comment]
Fixed the multiple event invocations issue. Will be publishing the next update ASAP.

**Comment by Willy-Kimura** [comment]
Published `v3.3.0` with fix.

**Comment by satyris** [comment]
Fix works on my side. Thanks!
